spring:
  application:
    name: Spotify
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_NAME:spotify}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          order_inserts: true
          order_updates: true
          batch_size: 30
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: # Your email
    password: # Your password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
        transport:
          protocol: smtp

jwt:
  secret: # Your Secret Key
  expiration: 3600

system:
  secret: # Your Secret Key

app:
  email:
    from: # Your email
    fromName: # Your name
  password-reset:
    expiration-hours: 24

server:
  port: 8080


management:
  prometheus:
    metrics:
      export:
        enabled: false
logging:
  level:
    root: info
    org.hibernate.sql: debug
    org.springframework: info

